name: Market Update

on:
  schedule:
    - cron: "30 19 * * *"  # 01:00 IST (19:30 UTC previous day)
    - cron: "0 0 * * *"    # 05:00 IST (00:00 UTC)
    - cron: "30 3 * * *"   # 09:00 IST (03:30 UTC)
    - cron: "30 7 * * *"   # 13:00 IST (07:30 UTC)
    - cron: "0 10 * * *"   # 15:00 IST (10:00 UTC)
    - cron: "30 13 * * *"  # 19:00 IST (13:30 UTC)
    - cron: "0 8 * * *"    # 13:30 IST (08:00 UTC, market)
    - cron: "0 15 * * *"   # 20:30 IST (15:00 UTC, market)
  workflow_dispatch:       # Allows manual trigger from GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust if you prefer a different version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run market update bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: |
          python market_update_bot.py "${{ github.event.schedule }}"
