name: Crypto Market Update
on:
  schedule:
    - cron: "30 20 * * *"  # 02:00 IST (News)
    - cron: "30 1 * * *"   # 07:00 IST (News)
    - cron: "0 6 * * *"    # 11:30 IST (News)
    - cron: "30 7 * * *"   # 13:00 IST (News)
    - cron: "0 8 * * *"    # 13:30 IST (Market)
    - cron: "30 9 * * *"   # 15:00 IST (News)
    - cron: "0 13 * * *"   # 18:30 IST (News)
    - cron: "30 14 * * *"  # 20:00 IST (News)
    - cron: "0 15 * * *"   # 20:30 IST (Market)
    - cron: "30 16 * * *"  # 22:00 IST (News)
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python market_update_bot.py "${{ github.event.schedule }}"
